# Generated by Django 3.0.2 on 2020-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200511_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
