# Generated by Django 3.0.2 on 2020-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_trendingarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
