# Generated by Django 3.1 on 2020-08-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_countryarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryArticle',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trendingarticle',
            name='image',
        ),
    ]
