# Generated by Django 3.0.2 on 2020-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_death', models.IntegerField()),
                ('total_confirmed', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
            ],
        ),
    ]
