# Generated by Django 3.0.2 on 2020-05-31 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
