# Generated by Django 3.0.2 on 2020-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_record_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unemployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=200)),
            ],
        ),
    ]
