# Generated by Django 3.0.2 on 2020-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20200601_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
