# Generated by Django 3.0.2 on 2020-06-25 08:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20200622_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
