# Generated by Django 3.0.2 on 2020-06-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20200628_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='confirmed_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='death_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='recovered_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='confirmed_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='death_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='recovered_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
