# Generated by Django 3.0.2 on 2020-07-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20200629_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('deaths', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
            ],
        ),
    ]
