# Generated by Django 3.0.2 on 2020-07-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='country',
            name='article_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='country',
            name='article_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='artile_title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
