# Generated by Django 3.0.2 on 2020-07-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20200713_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='country',
            name='article_link',
        ),
        migrations.RemoveField(
            model_name='country',
            name='artile_title',
        ),
    ]
