# Generated by Django 3.0.2 on 2020-07-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_countryarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryarticle',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Country'),
        ),
    ]
