# Generated by Django 3.1 on 2020-08-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20200714_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryArticle',
        ),
    ]
