# Generated by Django 3.1 on 2021-06-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_delete_countryarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='vaccination_count',
            field=models.IntegerField(default=0),
        ),
    ]
