# Generated by Django 3.1 on 2021-06-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_country_vaccination_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='vaccination_count',
            field=models.IntegerField(default=0),
        ),
    ]
