# Generated by Django 3.1 on 2021-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20210615_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='new_vaccination_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='new_vaccination_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
