# Generated by Django 3.1 on 2021-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0024_auto_20210615_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='vaccination_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='vaccination_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='vaccination_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='vaccination_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
