# Generated by Django 3.1 on 2021-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_auto_20210616_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfirmedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('total_confirmed', models.BigIntegerField()),
            ],
        ),
    ]
