# Generated by Django 3.1 on 2021-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_chartconfirmeddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartDeathData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('total_death', models.BigIntegerField()),
            ],
        ),
    ]
